Repository webaverse/app, pull requests merged in 2022-08, with the labels that each got.

#3436 Fix moving remove physics capsule
  character-controller.js
Labels: ready for qa

#3406 Fix clipped MegaHup
  src/MegaHup.jsx
  src/MegaHup.module.css
  src/components/general/character-select/CharacterSelect.jsx
Labels: ready for qa

#3305 Add Cryptoavatars
  diorama.js
  game.js
  package-lock.json
  public/images/disabled.png
  src/LightArrow.jsx
  src/LightArrow.module.css
  src/MegaHup.jsx
  src/components/app/App.jsx
  src/components/general/character-select/CharacterSelect.jsx
  src/components/general/character-select/character-select.module.css
  src/components/general/character-select/cryptoavatars-loader.js
Labels: ready for qa

#3438 login metamask
  public/images/ui/chainDown.svg
  public/images/ui/chainUp.svg
  src/User.jsx
  src/User.module.css
  src/components/app/App.jsx
  src/components/web3/chains.jsx
  src/components/web3/chains.module.css
  src/hooks/chainProvider.jsx
  src/hooks/rpcHelpers.js
  src/hooks/useChain.js
  src/hooks/useWeb3Account.js
  src/hooks/web3-constants.js
  src/hooks/web3AccountProvider.jsx
  src/main.jsx
Labels: ready for qa

#3523 Fix scene name url format
  src/components/editor-mode/scene-menu/SceneMenu.jsx
Labels: ready for qa

#3547 Fix missing reference to chatTextSpeed in constants.js
  src/RpgText.jsx
Labels: ready for qa

#3522 Store API key on AI setting window
  src/components/general/settings/TabAi.jsx
Labels: ready for qa

#3475 Let `getPlayerByAppInstanceId()` support npcPlayers.
  metaversefile-api.js
Labels: ready for qa

#3558 Fix "Emote animations do not blend when moving" issue.
  avatars/animationHelpers.js
Labels: animation

#3487 Avatar runs faster when tried with naruto run in crouch mode bug
  game.js
Labels: ready for qa

#3489 App would crash If avatar does not have springBones
  avatars/avatars.js
Labels: ready for qa

#3468 add abort flag
  metaverse_modules/firedrop/index.js
Labels: ready for qa

#3543 disable crouch if player is not on the ground
  game.js
  io-manager.js
Labels: ready for qa

#3444 Fixed mob manager issues.
  mob-manager.js
Labels: ready for qa

#3462 traverse on app instead of glb.scene
  character-physics.js
Labels: ready for qa

#3592 Fix bone chain accuracy
  avatars/avatars.js
  metaverse_components/wear.js
Labels: ready for qa

#3597 Fix "Avatar slides while in use action" issue.
  avatars/animationHelpers.js
Labels: animation

#3586 fix stretchy head issue
  avatars/avatars.js
Labels: ready for merge

#3526 dispatch use event false when dropping any app
  game.js
Labels: ready for merge

#3422 Fix wrong physical speed and animations jitter in low fps issues ( Make them "frame rate independent" ).
  avatars/animationHelpers.js
  avatars/avatars.js
  avatars/constants.js
  character-physics.js
  character-sfx.js
  constants.js
  game.js
  io-manager.js
  npc-manager.js
  player-avatar-binding.js
Labels: animation, Physics

#3456 Use default versions of scilia.vrm in Character select
  src/components/general/character-select/CharacterSelect.jsx
Labels: ready for merge

#3588 Revert app manager
  app-manager.js
Labels: ready for qa

#3593 Revert character controller commits
  app-manager.js
  character-controller.js
  constants.js
  interpolants.js
Labels: ready for qa

#3594 Revert hups
  src/CharacterHups.jsx
  src/MegaHup.jsx
Labels: ready for qa

#3511 Build for Vite
  .gitignore
  index.html
  index.mjs
  metaverse_modules/heal-effect/.metaversefile
  metaverse_modules/heal-effect/index.js
  moduleRewrite.js
  package.json
  pre.js
  vite.config.js
Labels: ready for qa

#3544 Notification component added for popup notifications
  src/PopupNotification.jsx
  src/PopupNotification.module.css
  src/components/app/App.jsx
  src/components/general/action-menu/ActionMenu.jsx
Labels: ready for qa
