Repository webaverse/app, pull requests merged in 2022-07, with the labels that each got.

#3220 Fix error if user clicks while loading
  transform-controls.js
Labels: ready for qa

#3221 Patch fix rigged mounts
  character-physics.js
Labels: ready for qa

#3227 Remove invalid call to updateAvatar on remote players
  players-manager.js
  webaverse.js
Labels: ready for qa

#3223 Refactor world and universe files
  src/components/editor-mode/scene-menu/SceneMenu.jsx
  universe.js
  voice-input/voice-input.js
  world.js
Labels: ready for qa

#3186 Implement PhysX Trigger Shapes.
  physics-manager.js
  physx.js
  public/bin/app-wasm-worker.js
  public/bin/app-wasm-worker.wasm
  public/bin/geometry.js
  public/bin/geometry.wasm
  scenes/scenes.json
  scenes/trigger.scn
  webaverse.js
Labels: Physics

#3237 Move Local Player code to PlayerBase to be shared
  character-controller.js
Labels: ready for qa

#3238 Change How We Handle Remote Avatar Interpolation
  character-controller.js
  interpolants.js
Labels: ready for qa

#3195 Don't play footsteps while character is sitting
  character-sfx.js
Labels: passed qa

#3218 Fix remote player use [E]
  avatars/animationHelpers.js
Labels: passed qa

#3228 Update scene selector to work with multiplayer and multiplayer rooms
  src/components/editor-mode/scene-menu/SceneMenu.jsx
Labels: passed qa

#3273 Fix `un/wear()` `un/grab()` not correctly `enable/disableGeometry(Queries)()` problem.
  character-controller.js
Labels: Physics

#3239 Separate avatar velocity from avatar update loop
  avatars/avatars.js
  player-avatar-binding.js
Labels: ready for qa

#3196 Sonic boom players for all players, not just localplayer
  character-fx.js
  character-sfx.js
  metaverse_modules/sonic-boom/index.js
Labels: awaiting dependency, ready for qa

#3241 Destroy remote players when players-manger is unbound
  players-manager.js
  universe.js
Labels: ready for qa

#3226 Fix error where Remote Player tries to sync a null avatar when initialized
  character-controller.js
Labels: ready for qa

#3243 Add remote update function to observer
  character-controller.js
Labels: awaiting dependency

#3222 Fix chat + local feedback in mic and add remote voice
  audio-manager.js
  avatars/avatars.js
  avatars/microphone-worklet.js
  character-controller.js
  character-hups.js
  chat-manager.js
  game.js
  music-manager.js
  src/CharacterHups.jsx
  voices.js
Labels: ready for qa

#3264 Pets: Work for all players (remote, etc) and look at nearest player, not just local player
  metaverse_components/pet.js
  metaversefile-api.js
Labels: ready for qa

#3251 Vertical swimming.
  avatars/animationHelpers.js
  avatars/avatars.js
  character-controller.js
  character-sfx.js
  constants.js
  player-avatar-binding.js
  scenes/water.scn
Labels: animation

#3289 Hide UI
  src/AvatarIcon.jsx
  src/Header.jsx
  src/User.jsx
  src/User.module.css
  src/components/app/App.jsx
  src/components/editor-mode/index.jsx
  src/components/editor-mode/scene-menu/SceneMenu.jsx
  src/components/general/action-menu/ActionMenu.jsx
  src/components/general/ui-mode/UIMode.jsx
  src/components/general/ui-mode/index.jsx
  src/components/general/ui-mode/ui-mode.module.css
  src/components/play-mode/hotbar/Hotbar.jsx
  src/components/play-mode/index.jsx
  src/components/play-mode/minimap/Minimap.jsx
Labels: ready for qa

#3203 Z nft blockchain
  drop-manager.js
  metaverse-modules.js
  package.json
  public/images/ui/chainDown.svg
  public/images/ui/chainUp.svg
  src/DragAndDrop.jsx
  src/Header.jsx
  src/LoadingBox.jsx
  src/ObjectPreview.jsx
  src/User.jsx
  src/User.module.css
  src/abis/Webaverse.json
  src/abis/WebaverseERC1155.json
  src/abis/WebaverseERC20.json
  src/abis/WebaverseVoucher.json
  src/abis/contract.jsx
  src/components/app/App.jsx
  src/components/general/equipment/Equipment.jsx
  src/components/general/equipment/equipment.module.css
  src/components/general/ui-mode/ui-mode.module.css
  src/components/play-mode/infobox/Infobox.jsx
  src/components/play-mode/mega-hotbox/MegaHotBox.jsx
  src/components/web3/NFTDetailsForm.jsx
  src/components/web3/chains.jsx
  src/components/web3/chains.module.css
  src/components/web3/nft-details-form.module.css
  src/hooks/chainProvider.jsx
  src/hooks/rpcHelpers.js
  src/hooks/useChain.js
  src/hooks/useNFTContract.js
  src/hooks/useWeb3Account.js
  src/hooks/voucherHelpers.js
  src/hooks/web3-constants.js
  src/hooks/web3AccountProvider.jsx
  src/main.jsx
  src/tabs/tokens.jsx
  util.js
Labels: ready for qa

#3225 Add nameplates above players heads in multiplayer
  character-fx.js
  metaverse-modules.js
  metaverse_modules/nameplate/.metaversefile
  metaverse_modules/nameplate/.nojekyll
  metaverse_modules/nameplate/index.js
  public/assets/nameplate.glb
Labels: awaiting dependency

#3329 Fix `fallLoop/land` jitter.
  avatars/animationHelpers.js
  avatars/avatars.js
  character-controller.js
  character-physics.js
  player-avatar-binding.js
Labels: animation

#3340 Implement PhysX Trigger Shapes. ( to master branch )
  physics-manager.js
  physx.js
  public/bin/app-wasm-worker.js
  public/bin/app-wasm-worker.wasm
  public/bin/geometry.js
  public/bin/geometry.wasm
  scenes/scenes.json
  scenes/trigger.scn
  webaverse.js
Labels: Physics

#3353 Fix `addConvexGeometry()` args mismatch issue.
  physics-manager.js
Labels: Physics

#3356 Add `addPlaneGeometry()` && Add infinite plane trigger to `trigger.scn`.
  metaversefile-api.js
  physics-manager.js
  physx.js
  public/bin/app-wasm-worker.js
  public/bin/app-wasm-worker.wasm
  public/bin/geometry.js
  public/bin/geometry.wasm
  scenes/trigger.scn
Labels: Physics

#3368 Upgrade the mobs bone texture definition
  mob-manager.js
Labels: ready for qa

#3377 Fix `addCookedConvexGeometry()`.
  physics-manager.js
  physx.js
Labels: Physics

#3383 Fix Duplicate World Tokens
  app-manager.js
Labels: ready for qa

#3378 consolidate players and remotePlayers to players manager
  camera-manager.js
  game.js
  loadout-manager.js
  mesh-lodder.js
  metaversefile-api.js
  mob-manager.js
  npc-manager.js
  overworld.js
  player-avatar-binding.js
  players-manager.js
  players.js
  scene-cruncher.js
  src/AvatarIcon.jsx
  src/CharacterHups.jsx
  src/DomRenderer.jsx
  story.js
  universe.js
  voices.js
  z-targeting.js
Labels: ready for qa

#3381 Fix remote player state (also fixes player messages)
  app-manager.js
  character-controller.js
  players-manager.js
  src/CharacterHups.jsx
Labels: ready for qa

#3366 Fixed wind effect issue when changing scene.
  avatars/simulation/wind.js
Labels: ready for qa

#3380 Press 'R' to log current state to console
  universe.js
  webaverse.js
Labels: ready for qa

#3347 Chat Diorama
  game.js
  src/CharacterHups.jsx
  src/MegaHup.jsx
Labels: ready for qa

#3426 Fix double avatars for local in multiplayer room
  character-controller.js
Labels: ready for qa
