Repository webaverse/app, pull requests merged in 2022-05, with the labels that each got.

#2785 Resolves #2126 app world editor uses rotation scn uses quaternions
  metaversefile-api.js
  object-screenshotter.js
  public/images/ui/gears-icon.svg
  public/images/ui/light-icon.svg
  public/images/ui/script-icon.svg
  src/components/app/App.jsx
  src/components/general/number-input/NumberInput.jsx
  src/components/general/number-input/index.jsx
  src/components/general/number-input/number-input.module.css
  src/components/general/object-screenshot/ObjectScreenshot.jsx
  src/components/general/object-screenshot/index.jsx
  src/components/general/object-screenshot/object-screenshot.module.css
  src/components/general/spritesheet/Spritesheet.jsx
  src/components/general/world-objects-list/WorldObjectsList.jsx
  src/components/general/world-objects-list/world-objects-list.module.css
  story.js
  webaverse.js
Labels: ui

#2931 VRArmIK Aim animation smooth lerp.
  avatars/avatars.js
  avatars/vrarmik/ShoulderTransforms.js
  character-controller.js
  constants.js
  player-avatar-binding.js
Labels: animation

#2998 2974 offscreen engine race condition
  constants.js
  offscreen-engine.js
Labels: frontend

#2969 Resolves #2126 app world editor uses rotation scn uses quaternions #2785
  object-screenshotter.js
  public/images/ui/gears-icon.svg
  public/images/ui/light-icon.svg
  public/images/ui/script-icon.svg
  src/components/app/App.jsx
  src/components/app/App.module.css
  src/components/general/number-input/NumberInput.jsx
  src/components/general/number-input/index.jsx
  src/components/general/number-input/number-input.module.css
  src/components/general/object-screenshot/ObjectScreenshot.jsx
  src/components/general/object-screenshot/index.jsx
  src/components/general/object-screenshot/object-screenshot.module.css
  src/components/general/spritesheet/Spritesheet.jsx
  src/components/general/world-objects-list/WorldObjectsList.jsx
  src/components/general/world-objects-list/world-objects-list.module.css
  story.js
  webaverse.js
Labels: ui

#3082 Pick up tree animation: Add one click logic.
  constants.js
  game.js
Labels: animation

#3088 3087 world objects panel does not work
  src/components/general/object-screenshot/ObjectScreenshot.jsx
  src/components/general/world-objects-list/component-editor.module.css
  src/components/general/world-objects-list/world-objects-list.module.css
Labels: ui
